version: "0.1.0"
slug: "stt"
name: "Speech-to-text API"
description: ""
url: "https://github.com/gabrielwong159/wyoming-stt-api"
arch:
  - aarch64
  - amd64
init: false
ports:
  10300/tcp: 10300
options:
  openai_api_key: null
  max_audio_duration_s: 10
schema:
  openai_api_key: str
  max_audio_duration_s: int
